server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3307/orders?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
    jackson:
      deserialization:
        fail-on-unknown-properties: true
        fail-on-ignored-properties: true
    mvc:
      throw-exception-if-no-handler-found: true
    logging:
      level:
        root: INFO
        org.springframework.web: DEBUG
  logging:
    file:
      path: /app/logs


resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enable: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED


