server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-33254313.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id:
            client-secret:
        provider:
          okta:
            issuer-uri: https://dev-33254313.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3307/orders?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
    jackson:
      deserialization:
        fail-on-unknown-properties: true
        fail-on-ignored-properties: true
    mvc:
      throw-exception-if-no-handler-found: true
    logging:
      level:
        root: INFO
        org.springframework.web: DEBUG
  logging:
    file:
      path: /app/logs




